ui.action.ids=move;build_arrow;sell;cancel
ui.action.move.label=Move
ui.action.move.hotkey=M
ui.action.move.entity_types=builder
ui.action.move.mode=move
ui.action.build_arrow.label=Build Arrow
ui.action.build_arrow.hotkey=B
ui.action.build_arrow.entity_types=builder
ui.action.build_arrow.mode=build
ui.action.build_arrow.tower_id=arrow
ui.action.sell.label=Sell
ui.action.sell.hotkey=X
ui.action.sell.entity_types=tower
ui.action.sell.mode=sell
ui.action.cancel.label=Cancel
ui.action.cancel.hotkey=C
ui.action.cancel.entity_types=builder;tower;none
ui.action.cancel.mode=cancel
