ui.action.ids=move;build;cancel
ui.action.move.label=Move
ui.action.move.hotkey=M
ui.action.move.entity_types=builder
ui.action.build.label=Build
ui.action.build.hotkey=B
ui.action.build.entity_types=builder
ui.action.cancel.label=Cancel
ui.action.cancel.hotkey=C
ui.action.cancel.entity_types=builder;tower;none
